config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("biblioteca.urls")),
    path("contas/", include("contas.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

# namespace para urls
# evita conflito de nomes
# permite usar urls do tipo 'app_name:name'
# Ex. 'dashboard:index'
app_name="dashboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("livros/", views.listar_livros, name="livros"),
    path("livros/criar/", views.criar_livro, name="criar-livro"),
    path("livros/<int:id>/", views.ler_livro, name="ler-livro"),
    path("livros/<int:id>/editar/", views.editar_livro, name="editar-livro"),
    path("livros/<int:id>/remover/", views.remover_livro, name="remover-livro"),
    path("usuarios/", views.listar_usuarios, name="usuarios"),
    path("usuarios/criar/", views.criar_usuario, name="criar-usuario"),
    path("usuarios/<int:id>/", views.ler_usuario, name="ler-usuario"),
    path("usuarios/<int:id>/editar/", views.editar_usuario, name="editar-usuario"),
    path("usuarios/<int:id>/remover/", views.remover_usuario, name="remover-usuario"),
]

biblioteca/models.py
from django.db import models
from django.conf import settings

class Livro(models.Model):
    ROMANCE = "RO"
    BIOGRAFIA = "BI"
    TECNICO = "TE"
    FICCAO = "FI"
    OUTROS = "OU"
    GENEROS = {
        ROMANCE: "Romance",
        BIOGRAFIA: "Biografia",
        TECNICO: "Técnico",
        FICCAO: "Ficção",
        OUTROS: "Outros",
    }

    titulo = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    ano = models.PositiveIntegerField()
    genero = models.CharField(max_length=2, choices=GENEROS)
    capa = models.ImageField(upload_to="biblioteca/capas/", blank=True)
    sinopse = models.TextField(blank=True)
    favoritos = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.titulo

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from biblioteca.models import Livro
from contas.models import Usuario

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = "__all__"
        exclude = ["favoritos"]

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from contas.models import Usuario
from biblioteca.models import Livro
from .forms import LivroForm
from contas.forms import UsuarioChangeForm, UsuarioCreationForm

@login_required
@permission_required("biblioteca.add_livro", raise_exception=True)
def index(request):

    context = {
        "num_livros": Livro.objects.count(),
        "num_usuarios": Usuario.objects.count(),
        "num_favoritos": Livro.favoritos.through.objects.count(),
    }

    return render(request, "dashboard/index.html", context)

@login_required
@permission_required("biblioteca.add_livro", raise_exception=True)
def listar_livros(request):
    ordenar = request.GET.get("ordenar")
    if ordenar:
        livros = Livro.objects.all().order_by(ordenar)
    else:
        livros = Livro.objects.all().order_by("id")

    paginator = Paginator(livros, 10)
    numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
    livros_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    return render(request, "dashboard/livros.html", {"livros": livros_paginados})

@login_required
@permission_required("biblioteca.add_livro", raise_exception=True)
def criar_livro(request):
    if request.method == "POST":
        form = LivroForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Livro criado com sucesso!")
            return redirect("dashboard:livros")
        else:
            messages.error(request, "Falha ao criar livro!")
    else:
        form = LivroForm()
    return render(request, "dashboard/criar_livro.html", {"form": form})

@login_required
@permission_required("biblioteca.view_livro", raise_exception=True)
def ler_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    return render(request, "dashboard/detalhar_livro.html", {"livro": livro})

@login_required
@permission_required("biblioteca.change_livro", raise_exception=True)
def editar_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    if request.method == "POST":
        form = LivroForm(request.POST, request.FILES, instance=livro)
        if form.is_valid():
            form.save()
            messages.success(request, "Livro atualizado!")
            return redirect("dashboard:livros")
        else:
            messages.error(request, "Falha ao criar livro!")
    else:
        form = LivroForm(instance=livro)
    return render(request, "dashboard/editar_livro.html", {"form": form})

def remover_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    if request.method == "POST":
        livro.delete()
        messages.success(request, "Livro removido com sucesso!")
        return redirect("dashboard:livros")
    else:
        return render(request, "dashboard/remover_livro.html")

def listar_usuarios(request):
    ordenar = request.GET.get("ordenar")
    if ordenar:
        usuarios = Usuario.objects.all().order_by(ordenar)
    else:
        usuarios = Usuario.objects.all().order_by("id")
    paginator = Paginator(usuarios, 10)
    numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
    usuarios_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    return render(request, "dashboard/usuarios.html", {"usuarios": usuarios_paginados})

def criar_usuario(request):
    if request.method == "POST":
        form = UsuarioCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuário criado com sucesso!")
            return redirect("dashboard:usuarios")
        else:
            messages.error(request, "Falha ao criar usuário!")
    else:
        form = UsuarioCreationForm()
    return render(request, "dashboard/criar_usuario.html", {"form": form})

def ler_usuario(request, id):
    usuario = get_object_or_404(Usuario, id=id)
    return render(request, "dashboard/detalhar_usuario.html", {"usuario": usuario})

def editar_usuario(request, id):
    usuario = get_object_or_404(Usuario, id=id)
    if request.method == "POST":
        form = UsuarioChangeForm(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuário atualizado!")
            return redirect("dashboard:usuarios")
        else:
            messages.error(request, "Falha ao criar usuário!")
    else:
        form = UsuarioChangeForm(instance=usuario)
    return render(request, "dashboard/editar_usuario.html", {"form": form})

def remover_usuario(request, id):
    usuario = get_object_or_404(Usuario, id=id)
    if request.method == "POST":
        if usuario.id == request.user.id:
            messages.error(request, "Não é possível remover o usuário logado!")
        else:
            usuario.delete()
            messages.success(request, "Usuário removido com sucesso!")
        return redirect("dashboard:usuarios")
    else:
        return render(request, "dashboard/remover_usuario.html")

templates/dashboard/partials/_detalhar_livro.html
<div class="row">
  <div class="col">
    <h3>{{livro.titulo}}</h3>
    <p>Autor: {{livro.autor}}</p>
    <p>Ano: {{livro.ano}}</p>
    <p>Gênero: {{livro.get_genero_display}}</p>
    <p>Favoritos: {{livro.favoritos.count}}</p>
    <a href="{% url 'dashboard:livros' %}">Voltar</a>
    <a href="{% url 'dashboard:editar-livro' livro.id %}">Editar</a>
    <a href="{% url 'dashboard:remover-livro' livro.id %}">Remover</a>
  </div>
  <div class="col">
    <img src="{{ livro.capa.url }}" width=300 alt="capa">
  </div>
</div>

templates/dashboard/partials/_detalhar_usuario.html
<div class="row">
  <div class="col">
    {% if usuario.avatar %}
      <img src="{{ usuario.avatar.url }}" width=300 alt="capa">
    {% endif %}
  </div>
  <div class="col">
    <h3>{{usuario.username}}</h3>
    <p>Nome: {{usuario.first_name}}</p>
    <p>Sobrenome: {{usuario.last_name}}</p>
    <p>Data de Nascimento: {{usuario.nascimento}}</p>
    <p>Idade: {{usuario.idade}}</p>
    <p>Favoritos: {{usuario.favoritos.count}}</p>
    <a href="{% url 'dashboard:usuarios' %}">Voltar</a>
    <a href="{% url 'dashboard:editar-usuario' usuario.id %}">Editar</a>
    <a href="{% url 'dashboard:remover-usuario' usuario.id %}">Remover</a>
  </div>
</div>

templates/dashboard/partials/_form_livro.html
{% load crispy_forms_tags %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Salvar</button>
  <a href="{% url 'dashboard:livros' %}" class="btn btn-secondary">Cancelar</a>
</form>

templates/dashboard/partials/_form_usuario.html
{% load crispy_forms_tags %}
<form method="post" enctype="multipart/form-data">
  <style type="text/css" media="all">
    .form-text {
      display: none;
    }
  </style>
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">Salvar</button>
  <a href="{% url 'dashboard:usuarios' %}" class="btn btn-secondary">Cancelar</a>
</form>

templates/dashboard/partials/_remover_livro.html
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Remover</button>
  <a href="{% url 'dashboard:livros' %}" class="btn btn-secondary" role="button">Cancelar</a>
</form>

templates/dashboard/partials/_remover_usuario.html
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Remover</button>
  <a href="{% url 'dashboard:usuarios' %}" class="btn btn-secondary" role="button">Cancelar</a>
</form>

templates/dashboard/partials/_tabela_livros.html
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th scope="col"><a href="{% querystring ordenar='id' %}" >#</a></th>
        <th scope="col"><a href="{% querystring ordenar='titulo' %}" >Título<a></th>
        <th scope="col"><a href="{% querystring ordenar='autor' %}" >Autor</a></th>
        <th scope="col"><a href="{% querystring ordenar='ano' %}" >Ano</a></th>
        <th scope="col"><a href="{% querystring ordenar='genero' %}" >Gênero</a></th>
        <th scope="col"><a href="{% querystring ordenar='favoritos' %}" >Favoritos</a></th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
  {% for livro in livros %}
    <tr>
      <td>
        {{ livro.id }} 
      </td>  
      <td>
        {{ livro.titulo }} 
      </td>  
      <td>
        {{ livro.autor }} 
      </td>  
      <td>
        {{ livro.ano }} 
      </td>  
      <td>
        {{ livro.get_genero_display }} 
      </td>  
      <td>
        {{ livro.favoritos.count }} 
      </td>  
      <td class="text-nowrap">
        <a href="{% url 'dashboard:ler-livro' livro.id %}" class="btn btn-primary"><i class="bi bi-eye-fill"></i></a>
        <a href="{% url 'dashboard:editar-livro' livro.id %}" class="btn btn-secondary"><i class="bi bi-pencil-fill"></i></a>
        <a href="{% url 'dashboard:remover-livro' livro.id %}" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
      </td>  
    </tr>
  {% endfor %}
    </tbody>
  </table>
</div>
  <!-- Navegação da paginação -->
{% if livros.paginator.num_pages > 1 %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item {{  livros.has_previous|yesno:',disabled,disabled'  }}">
        <a class="page-link" href="{% if livros.has_previous %}{% querystring p=livros.previous_page_number %}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% for page in livros.paginator.page_range %}
      <li class="page-item"><a class="page-link {% if livros.number == page %}active{% endif %}" href="{% querystring p=page %}">{{page}}</a></li>
      {% endfor %}
      <li class="page-item {{  livros.has_next|yesno:',disabled,disabled'  }}">
        <a class="page-link" href="{% if livros.has_next %}{% querystring p=livros.next_page_number %}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endif %}

templates/dashboard/partials/_tabela_usuarios.html
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th scope="col"><a href="{% querystring ordenar='id' %}" >#</a></th>
        <th scope="col"><a href="{% querystring ordenar='username' %}" >Username<a></th>
        <th scope="col"><a href="{% querystring ordenar='first_name' %}" >Nome</a></th>
        <th scope="col"><a href="{% querystring ordenar='last_name' %}" >Sobrenome</a></th>
        <th scope="col"><a href="{% querystring ordenar='-nascimento' %}" >Idade</a></th>
        <th scope="col"><a href="{% querystring ordenar='livro' %}" >Favoritos</a></th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
  {% for usuario in usuarios %}
    <tr>
      <td>
        {{ usuario.id }} 
      </td>  
      <td>
        {{ usuario.username }} 
      </td>  
      <td>
        {{ usuario.first_name }} 
      </td>  
      <td>
        {{ usuario.last_name }} 
      </td>  
      <td>
        {{ usuario.idade }} 
      </td>  
      <td>
        {{ usuario.livro_set.count }} 
      </td>  
      <td class="text-nowrap">
        <a href="{% url 'dashboard:ler-usuario' usuario.id %}" class="btn btn-primary"><i class="bi bi-eye-fill"></i></a>
        <a href="{% url 'dashboard:editar-usuario' usuario.id %}" class="btn btn-secondary"><i class="bi bi-pencil-fill"></i></a>
        <!-- não mostra o remover caso seja o próprio usuário logado -->
        {% if user.id == usuario.id %}
        <button class="btn btn-danger" disabled><i class="bi bi-trash-fill"></i></button>
        {% else %}
        <a href="{% url 'dashboard:remover-usuario' usuario.id %}" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
        {% endif %}
      </td>  
    </tr>
  {% endfor %}
    </tbody>
  </table>
</div>
  <!-- Navegação da paginação -->
{% if livros.paginator.num_pages > 1 %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item {{  livros.has_previous|yesno:',disabled,disabled'  }}">
        <a class="page-link" href="{% if livros.has_previous %}{% querystring p=livros.previous_page_number %}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% for page in livros.paginator.page_range %}
      <li class="page-item"><a class="page-link {% if livros.number == page %}active{% endif %}" href="{% querystring p=page %}">{{page}}</a></li>
      {% endfor %}
      <li class="page-item {{  livros.has_next|yesno:',disabled,disabled'  }}">
        <a class="page-link" href="{% if livros.has_next %}{% querystring p=livros.next_page_number %}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endif %}