biblioteca/urls.py
from django.urls import path
from . import views

# namespace para urls
# evita conflito de nomes
# permite usar urls do tipo 'app_name:name'
# Ex. 'biblioteca:index'
app_name="biblioteca"
urlpatterns = [
    path("", views.index, name="index"),
    path("livros/", views.livros, name="livros"),
    path("livro/<int:id_livro>/", views.detalhar_livro, name="detalhar_livro"),
    path("pesquisa/", views.pesquisa, name="pesquisa"),
    path("meus-livros/", views.meus_livros, name="meus-livros"),
    path("favoritar/<int:id_livro>/", views.favoritar, name="favoritar"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("biblioteca.urls")),
    path("contas/", include("contas.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/models.py
from django.db import models
from django.conf import settings

class Livro(models.Model):
    ROMANCE = "RO"
    BIOGRAFIA = "BI"
    TECNICO = "TE"
    FICCAO = "FI"
    OUTROS = "OU"
    GENEROS = {
        ROMANCE: "Romance",
        BIOGRAFIA: "Biografia",
        TECNICO: "Técnico",
        FICCAO: "Ficção",
        OUTROS: "Outros",
    }

    titulo = models.CharField(max_length=100)
    autor = models.CharField(max_length=100)
    ano = models.PositiveIntegerField()
    genero = models.CharField(max_length=2, choices=GENEROS)
    capa = models.ImageField(upload_to="biblioteca/capas/", blank=True)
    sinopse = models.TextField(blank=True)
    favoritos = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.titulo

biblioteca/forms.py
from django import forms
from .models import Livro

class GeneroForm(forms.Form):
    generos = forms.ChoiceField(choices=Livro.GENEROS)

biblioteca/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Livro
from .forms import GeneroForm
from contas.models import Usuario

def index(request):
    livros = Livro.objects.all().order_by("?")[:6]
    return render(request, "biblioteca/index.html", {"livros": livros})

def livros(request):
    filtro = request.GET.get("f")
    if filtro and filtro in Livro.GENEROS:
        livros = Livro.objects.filter(genero=filtro).order_by("id")
    else:
        livros = Livro.objects.all().order_by("id")
    paginator = Paginator(livros, 6)
    numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
    livros_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    return render(request, "biblioteca/livros.html", {"livros": livros_paginados, "opcoes": Livro.GENEROS.items()})

def detalhar_livro(request, id_livro):
    livro = get_object_or_404(Livro, id=id_livro)
    return render(request, "biblioteca/detalhar_livro.html", {"livro": livro})

def pesquisa(request):
    pesquisa = request.GET.get("q")
    if pesquisa:
        # pesquisa nos autores
        livros_autor = Livro.objects.filter(autor__icontains=pesquisa)
        # pesquisa nos títulos
        livros_titulo = Livro.objects.filter(titulo__icontains=pesquisa)
        # pesquisa na sinopse
        livros_sinopse = Livro.objects.filter(sinopse__icontains=pesquisa)
        # junta os 3 resultados
        livros = livros_autor | livros_titulo | livros_sinopse
        # retira os resultados duplicados
        livros.distinct() 
    
        paginator = Paginator(livros, 6)
        numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
        livros_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    else:
        livros_paginados = [] # se não houver termo de pesquisa, retorna nada
    return render(request, "biblioteca/pesquisa.html", {"livros": livros_paginados})

@login_required
def meus_livros(request):
    livros = Livro.objects.filter(favoritos__id=request.user.id).order_by("id")
    paginator = Paginator(livros, 6)
    numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
    livros_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    return render(request, "biblioteca/meus_livros.html", {"livros": livros_paginados})

@login_required
def favoritar(request, id_livro):
    if request.POST:
        livro = get_object_or_404(Livro, id=id_livro)
        if request.user in livro.favoritos.all():
            livro.favoritos.remove(request.user)
            messages.success(request, "Livro removido com sucesso!")
        else:
            livro.favoritos.add(request.user)
            messages.success(request, "Livro favoritado com sucesso!")
    else:
        messages.erros(request, "Falha ao favoritar o livro!")

    return redirect("biblioteca:meus-livros")

templates/biblioteca/partials/_card_livro.html
{% load static %}
<div class="col">
  <div class="card mb-3 shadow-sm h-100" style="max-width: 540px;">
    <div class="row g-0 h-100">
      <div class="col-md-4">
        {% if livro.capa %}
        <img src="{{ livro.capa.url }}" class="img-fluid rounded-start w-100 h-100 object-fit-cover" alt="capa">
        {% else %}
        <img src="{% static 'biblioteca/placeholder/capa.png' %}" class="card-img-top w-75 mx-auto border border-2" alt="capa">
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body h-100">
          <h4 class="card-title">{{ livro.titulo }}</h4>
          <div class="card-text">
            <p>{{ livro.autor }}</p>
            <p>{{ livro.get_genero_display }}</p>
            <p>{{ livro.ano }}</p>
          </div>
          <div class="d-flex align-items-bottom justify-content-center gap-2 mt-auto">
            <a href="{% url 'biblioteca:detalhar_livro' livro.id %}" class="btn btn-primary" role="button">Detalhar</a>
            {% if request.user.is_authenticated %}
            <form action="{% url 'biblioteca:favoritar' livro.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger">
                <span>{{ livro.favoritos.count }}</span>
                {% if request.user in livro.favoritos.all %}
                <i class="bi bi-heart-fill ms-1"></i>
                {% else %}
                <i class="bi bi-heart ms-1"></i>
                {% endif %}
              </button>
            </form>
            {% else %}
            <a class="btn btn-outline-danger disabled" role="button" aria-disabled="true">
              <span>{{ livro.favoritos.count }}</span>
              {% if request.user in livro.favoritos.all %}
              <i class="bi bi-heart-fill ms-1"></i>
              {% else %}
              <i class="bi bi-heart ms-1"></i>
              {% endif %}
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/biblioteca/partials/_detalhar_livro.html
<div class="row">
  <div class="col">
    <img src="{{ livro.capa.url }}" width=300 alt="capa">
  </div>
  <div class="col">
    <h3>{{livro.titulo}}</h3>
    <p>Autor: {{livro.autor}}</p>
    <p>Ano: {{livro.ano}}</p>
    <p>Gênero: {{livro.get_genero_display}}</p>
    <p>Sinopse: {{livro.sinopse}}</p>
    <p>Favoritos: {{livro.favoritos.count}}</p>
    <a href="{% url 'biblioteca:livros' %}">Voltar</a>
  </div>
</div>

templates/biblioteca/partials/_galeria_livros.html
{% load static %}
<div class="container">
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3 mb-3">
{% for livro in livros %}
{% include 'biblioteca/partials/_card_livro.html' %}
{% empty %}
<h1>Não há livros cadastrados!</h1>
{% endfor %}
  </div>
  <!-- Navegação da paginação -->
{% if livros.paginator.num_pages > 1 %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item {{  livros.has_previous|yesno:',disabled,disabled'  }}">
        <a class="page-link" href="{% if livros.has_previous %}{% querystring p=livros.previous_page_number %}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% for page in livros.paginator.page_range %}
      <li class="page-item"><a class="page-link {% if livros.number == page %}active{% endif %}" href="{% querystring p=page %}">{{page}}</a></li>
      {% endfor %}
      <li class="page-item {{  livros.has_next|yesno:',disabled,disabled'  }}">
        <a class="page-link" href="{% if livros.has_next %}{% querystring p=livros.next_page_number %}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endif %}
</div>