biblioteca/urls.py
from django.urls import path
from . import views

# namespace para urls
# evita conflito de nomes
# permite usar urls do tipo 'app_name:name'
# Ex. 'biblioteca:index'
app_name="biblioteca"
urlpatterns = [
    path("", views.index, name="index"),
    path("livros/", views.livros, name="livros"),
    path("livro/<int:id_livro>/", views.detalhar_livro, name="detalhar_livro"),
    path("pesquisa/", views.pesquisa, name="pesquisa"),
    path("meus-livros/", views.meus_livros, name="meus-livros"),
    path("favoritar/<int:id_livro>/", views.favoritar, name="favoritar"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("biblioteca.urls")),
    path("contas/", include("contas.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Biblioteca | {% block title %}Início{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <header class="sticky-top bg-light border-bottom shadow-sm">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand fs-4" href="{% url 'biblioteca:index' %}">
            <i class="bi-book-half" style="color: blue; height: 80;"></i>
            Biblioteca
          </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'biblioteca:index' %}">Início</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'biblioteca:livros' %}">Livros</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'biblioteca:meus-livros' %}">Meus Livros</a>
              </li>
              {% endif %}
              {% if request.user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
              </li>
              {% endif %}
            </ul>
            <form action="{% url 'biblioteca:pesquisa' %}" class="d-flex me-lg-2" role="search">
              <div class="input-group">
                <input class="form-control" type="search" placeholder="Pesquisar" name="q" aria-label="Pesquisar" aria-describedby="button-busca">
                <button class="btn btn-outline-secondary" type="submit" id="button-busca">
                  <i class="bi-search"></i>
                </button>
              </div>
            </form>
          </div>
          {% if request.user.is_authenticated %}
          <div class="dropdown mt-2 mt-lg-0">
            <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              {% if request.user.avatar %}
              <img src="{{ request.user.avatar.url }}" alt="mdo" width="32" height="32" class="ms-1 rounded-circle object-fit-cover">
              {% else %}
              <img src="{% static 'biblioteca/placeholder/avatar.png' %}" alt="mdo" width="32" height="32" class="ms-1 rounded-circle object-fit-cover">
              {% endif %}
            </a>
            <ul class="dropdown-menu text-small shadow mt-2 dropdown-menu-end" style="">
              <li><a class="dropdown-item" href="{% url 'perfil' %}">Perfil</a></li>
              <li><a class="dropdown-item" href="{% url 'password_change' %}">Alterar Senha</a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button class="dropdown-item" type="submit">Sair</button></li>
                </form>
            </ul>
          </div>
          {% else %}
          <div class="text-center mt-2 mt-lg-0">
            <a href="{% url 'login' %}" role="button" class="btn btn-primary">Login</a>
          </div>
          {% endif %}
        </div>
      </nav>
    </header>

    {% if messages %}
    <div>
      {% for message in messages %}
        <!-- o bootstrap não tem "alert-error", entao aqui converte
          pra "alert-danger -->
        {% if message.tags == "error" %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {% endif %}
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </div>
    {% endif %}


    <main class="flex-grow-1">
    {% block content %}
      <h1>Conteúdo</h1>
    {% endblock content %}
    </main>

    <footer class="text-body-secondary py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Voltar ao topo</a>
        </p>
        <p class="mb-1">Programação de Sistemas para Internet - IFRN/SPP - {% now 'Y' %}</p>
        <p class="mb-0"><a href="https://dvcirilo.github.io/psi-ifrn">Material de aula</a>.</p>
      </div>
    </footer>
  </body>
</html>