config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("biblioteca.urls")),
    path("contas/", include("contas.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

# namespace para urls
# evita conflito de nomes
# permite usar urls do tipo 'app_name:name'
# Ex. 'dashboard:index'
app_name="dashboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("livros/", views.listar_livros, name="livros"),
    path("livros/criar/", views.criar_livro, name="criar-livro"),
    path("livros/<int:id>/", views.ler_livro, name="ler-livro"),
    path("livros/<int:id>/editar/", views.editar_livro, name="editar-livro"),
    path("livros/<int:id>/remover/", views.remover_livro, name="remover-livro"),
    path("usuarios/", views.listar_usuarios, name="usuarios"),
    path("usuarios/criar/", views.criar_usuario, name="criar-usuario"),
    path("usuarios/<int:id>/", views.ler_usuario, name="ler-usuario"),
    path("usuarios/<int:id>/editar/", views.editar_usuario, name="editar-usuario"),
    path("usuarios/<int:id>/remover/", views.remover_usuario, name="remover-usuario"),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from biblioteca.models import Livro
from contas.models import Usuario

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = "__all__"
        exclude = ["favoritos"]

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from contas.models import Usuario
from biblioteca.models import Livro
from .forms import LivroForm
from contas.forms import UsuarioChangeForm, UsuarioCreationForm

@login_required
@permission_required("biblioteca.add_livro", raise_exception=True)
def index(request):

    context = {
        "num_livros": Livro.objects.count(),
        "num_usuarios": Usuario.objects.count(),
        "num_favoritos": Livro.favoritos.through.objects.count(),
    }

    return render(request, "dashboard/index.html", context)

@login_required
@permission_required("biblioteca.add_livro", raise_exception=True)
def listar_livros(request):
    ordenar = request.GET.get("ordenar")
    if ordenar:
        livros = Livro.objects.all().order_by(ordenar)
    else:
        livros = Livro.objects.all().order_by("id")

    paginator = Paginator(livros, 10)
    numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
    livros_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    return render(request, "dashboard/livros.html", {"livros": livros_paginados})

@login_required
@permission_required("biblioteca.add_livro", raise_exception=True)
def criar_livro(request):
    if request.method == "POST":
        form = LivroForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Livro criado com sucesso!")
            return redirect("dashboard:livros")
        else:
            messages.error(request, "Falha ao criar livro!")
    else:
        form = LivroForm()
    return render(request, "dashboard/criar_livro.html", {"form": form})

@login_required
@permission_required("biblioteca.view_livro", raise_exception=True)
def ler_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    return render(request, "dashboard/detalhar_livro.html", {"livro": livro})

@login_required
@permission_required("biblioteca.change_livro", raise_exception=True)
def editar_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    if request.method == "POST":
        form = LivroForm(request.POST, request.FILES, instance=livro)
        if form.is_valid():
            form.save()
            messages.success(request, "Livro atualizado!")
            return redirect("dashboard:livros")
        else:
            messages.error(request, "Falha ao criar livro!")
    else:
        form = LivroForm(instance=livro)
    return render(request, "dashboard/editar_livro.html", {"form": form})

def remover_livro(request, id):
    livro = get_object_or_404(Livro, id=id)
    if request.method == "POST":
        livro.delete()
        messages.success(request, "Livro removido com sucesso!")
        return redirect("dashboard:livros")
    else:
        return render(request, "dashboard/remover_livro.html")

def listar_usuarios(request):
    ordenar = request.GET.get("ordenar")
    if ordenar:
        usuarios = Usuario.objects.all().order_by(ordenar)
    else:
        usuarios = Usuario.objects.all().order_by("id")
    paginator = Paginator(usuarios, 10)
    numero_da_pagina = request.GET.get('p')  # Pega o número da página da URL
    usuarios_paginados = paginator.get_page(numero_da_pagina)  # Pega a página específica
    return render(request, "dashboard/usuarios.html", {"usuarios": usuarios_paginados})

def criar_usuario(request):
    if request.method == "POST":
        form = UsuarioCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuário criado com sucesso!")
            return redirect("dashboard:usuarios")
        else:
            messages.error(request, "Falha ao criar usuário!")
    else:
        form = UsuarioCreationForm()
    return render(request, "dashboard/criar_usuario.html", {"form": form})

def ler_usuario(request, id):
    usuario = get_object_or_404(Usuario, id=id)
    return render(request, "dashboard/detalhar_usuario.html", {"usuario": usuario})

def editar_usuario(request, id):
    usuario = get_object_or_404(Usuario, id=id)
    if request.method == "POST":
        form = UsuarioChangeForm(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuário atualizado!")
            return redirect("dashboard:usuarios")
        else:
            messages.error(request, "Falha ao criar usuário!")
    else:
        form = UsuarioChangeForm(instance=usuario)
    return render(request, "dashboard/editar_usuario.html", {"form": form})

def remover_usuario(request, id):
    usuario = get_object_or_404(Usuario, id=id)
    if request.method == "POST":
        if usuario.id == request.user.id:
            messages.error(request, "Não é possível remover o usuário logado!")
        else:
            usuario.delete()
            messages.success(request, "Usuário removido com sucesso!")
        return redirect("dashboard:usuarios")
    else:
        return render(request, "dashboard/remover_usuario.html")

templates/dashboard/base.html
{% extends "base.html" %}
{% load static %}

{% block title %}Início{% endblock %}

{% block content %}
<div class="container-fluid h-100">
  <div class="row">
    <aside class="col col-md-2 bg-body-secondary position-sticky top-0">  <!-- sidebar -->
      <ul class="nav nav-pills flex-column mb-auto">
        <li>
          <a href="{% url 'dashboard:index' %}" class="nav-link{% if request.resolver_match.url_name == 'index' %} active{% else %} link-body-emphasis{% endif %}">
            <i class="bi bi-speedometer2 me-2"></i>
            Dashboard
          </a>
        </li>
        <li>
          <a href="{% url 'dashboard:livros' %}" class="nav-link{% if request.resolver_match.url_name == 'livros' %} active{% else %} link-body-emphasis{% endif %}">
            <i class="bi bi-book me-2"></i>
            Livros
          </a>
        </li>
        <li>
          <a href="{% url 'dashboard:usuarios' %}" class="nav-link{% if request.resolver_match.url_name == 'usuarios' %} active{% else %} link-body-emphasis{% endif %}">
            <i class="bi bi-person-circle me-2"></i>
            Usuários
          </a>
        </li>
      </ul>
    </aside>
    <div class="col col-md-10">
      <div class="container-fluid p-4">
        <div class="container d-flex">
          {% block page-title %}
          <h3 class="display-3 me-auto"> Administração </h3>
          {% endblock %}
        </div>
        {% block dashboard-content %}
           
        {% endblock %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/dashboard/criar_livro.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Criar Livro{% endblock %}
{% block page-title %}<h3 class="display-3">Criar Livro</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_form_livro.html" %}
</div>
{% endblock %}

templates/dashboard/criar_usuario.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Criar Usuário{% endblock %}
{% block page-title %}<h3 class="display-3">Criar Usuário</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_form_usuario.html" %}
</div>
{% endblock %}

templates/dashboard/detalhar_livro.html
{% extends "dashboard/base.html" %}

{% block title %}Detalhar Livro{% endblock %}
{% block page-title %}<h3 class="display-3">Detalhar Livro</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_detalhar_livro.html" %}
</div>
{% endblock %}

templates/dashboard/detalhar_usuario.html
{% extends "dashboard/base.html" %}

{% block title %}Detalhar Usuário{% endblock %}
{% block page-title %}<h3 class="display-3">Detalhar Usuário</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_detalhar_usuario.html" %}
</div>
{% endblock %}

templates/dashboard/editar_livro.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Editar Livro{% endblock %}
{% block page-title %}<h3 class="display-3">Editar Livro</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_form_livro.html" %}
</div>
{% endblock %}

templates/dashboard/editar_usuario.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Editar Usuário{% endblock %}
{% block page-title %}<h3 class="display-3">Editar Usuário</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_form_usuario.html" %}
</div>
{% endblock %}

templates/dashboard/index.html
{% extends "dashboard/base.html" %}

{% block title %}Dashboard{% endblock %}
{% block page-title %}
<h3 class="display-3 me-auto"> Dashboard </h3>
{% endblock %}

{% block dashboard-content %}
<section class="album py-5 bg-body-tertiary">
  <div class="row">
    <div class="col-md-4">
      <a class="text-decoration-none" style="color: inherit;" href="{% url 'dashboard:usuarios' %}">
        <div class="card text-bg-primary mb-3">
          <div class="card-body">

            <h5 class="card-title">Usuários</h5>
            <p class="card-text">Total: {{ num_usuarios }}</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4">
      <a class="text-decoration-none" style="color: inherit;" href="{% url 'dashboard:livros' %}">
        <div class="card text-bg-success mb-3">
          <div class="card-body">
            <h5 class="card-title">Livros</h5>
            <p class="card-text">Total: {{ num_livros }}</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-4">
      <div class="card text-bg-warning mb-3">
        <div class="card-body">
          <h5 class="card-title">Favoritos</h5>
            <p class="card-text">Total: {{ num_favoritos }}</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/dashboard/livros.html
{% extends "dashboard/base.html" %}
{% block page-title %}
<h2 class="display-2 me-auto">Livros</h2>
<div class="d-flex align-items-center">
  <a class="btn btn-primary" href="{% url 'dashboard:criar-livro' %}">Novo</a>
</div>
{% endblock %}
{% block dashboard-content %}
{% include 'dashboard/partials/_tabela_livros.html' %}
{% endblock %}

templates/dashboard/remover_livro.html
{% extends "dashboard/base.html" %}

{% block title %}Remover Livro{% endblock %}
{% block page-title %}<h3 class="display-3">Remover Livro</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_remover_livro.html" %}
</div>
{% endblock %}

templates/dashboard/remover_usuario.html
{% extends "dashboard/base.html" %}

{% block title %}Remover Usuário{% endblock %}
{% block page-title %}<h3 class="display-3">Remover Usuário</h3>{% endblock %}

{% block dashboard-content %}
<div style="min-width: 300px;">
  {% include "dashboard/partials/_remover_usuario.html" %}
</div>
{% endblock %}

templates/dashboard/usuarios.html
{% extends "dashboard/base.html" %}
{% block page-title %}
<h2 class="display-2 me-auto">Usuários</h2>
<div class="d-flex align-items-center">
  <a class="btn btn-primary" href="{% url 'dashboard:criar-usuario' %}">Novo</a>
</div>
{% endblock %}

{% block dashboard-content %}
{% include 'dashboard/partials/_tabela_usuarios.html' %}
{% endblock %}